service: serverless-aws-api

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-south-1
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.postsTableName}

custom:
  postsTableName: posts-table-${self:provider.stage}

plugins:
  - serverless-iam-roles-per-function

functions:
  getPost:
    handler: api.getPost
    name: get-post
    memorySize: 128 #MB
    timeout: 5 #seconds
    events:
      - http:
          path: posts/{postId}
          method: GET
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - 'dynamodb:GetItem' 
        Resource: !GetAtt PostsTable.Arn
  createPost:
    handler: api.createPost
    name: create-post
    memorySize: 128 #MB
    timeout: 5 #seconds
    events:
      - http:
          path: posts
          method: POST 
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - 'dynamodb:PutItem' 
        Resource: !GetAttr PostsTable.Arn
  updatePost:
    handler: api.updatePost
    name: update-post
    memorySize: 128 #MB
    timeout: 5 #seconds
    events:
      - http:
          path: posts/{postId}
          method: PUT 
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - 'dynamodb:UpdateItem' 
        Resource: !GetAttr PostsTable.Arn
  deletePost:
    handler: api.deletePost
    name: delete-post
    memorySize: 128 #MB
    timeout: 5 #seconds
    events:
      - http:
          path: posts/{postId}
          method: DELETE 
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - 'dynamodb:DeleteItem' 
        Resource: !GetAttr PostsTable.Arn
  getAllPost:
    handler: api.getAllPost
    name: get-all-post
    memorySize: 128 #MB
    timeout: 5 #seconds
    events:
      - http:
          path: posts
          method: GET 
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - 'dynamodb:Scan' 
        Resource: !GetAttr PostsTable.Arn


resources:
  Resources:
    PostsTable:
      Type: AWS::DynamoDB::TABLE
      Properties:
        TableName: ${custom.postsTableName}
        AttributeDefinitions:
          - AttributeName: postId
            AttributeType: S
        KeySchema:
          - AttributeName: postId
            AttributeType: HASH
        ProvisionedThroughput:
          - ReadCapacityUnits: 1
          - WriteCapacityUnits: 1
